import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'

const figtree = Figtree({
  subsets: [ 'latin' ],
  fallback: [
    '-apple-system',
    'BlinkMacSystemFont',
    'avenir next',
    'avenir',
    'segoe ui',
    'helvetica neue',
    'helvetica',
    'Cantarell',
    'Ubuntu',
    'roboto',
    'noto',
    'arial',
    'sans-serif'
  ]
})

export const metadata: Metadata = {
  title: "Junior Social Innovator Program",
  description: "Generated by synced labs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
